import { initializeApp } from "firebase/app";
import { getFirestore, collection, addDoc } from "firebase/firestore"; // Importa Firestore

// Configuración de Firebase (obtén esto desde la consola de Firebase)
const firebaseConfig = {
  apiKey: "AIzaSyAqnMhZ3u-z1hqlqGod7qUo7bb6PLIF_dI",
  authDomain: "dynamic-dam.firebaseapp.com",
  projectId: "dynamic-dam",
  storageBucket: "dynamic-dam.firebasestorage.app",
  messagingSenderId: "610391208242",
  appId: "1:610391208242:web:31647d9cc6a9ee9b47a72b",
  measurementId: "G-GJFL7VPG07"
};
const app = initializeApp(firebaseConfig);

const db = getFirestore(app); // Inicializa Firestore

export const clientes = [
    {
        APagar: "50 €",
        Altura: 1.70,
        Apellido1: "González",
        Apellido2: "Martínez",
        Contraseña: "",
        Email: "carlosg@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "13/09/1999",
        Genero: "Masculino",
        Nombre: "Carlos",
        Peso: 79,
        PlanSuscripcion: "Mensual",
        Telefono: 625849200,
        UdGimnasio: "123456789",
        validated: false
    },
    {
        APagar: "600 €",
        Altura: 1.65,
        Apellido1: "Pérez",
        Apellido2: "Ramírez",
        Contraseña: "",
        Email: "maria.perez@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "25/04/1995",
        Genero: "Femenino",
        Nombre: "María",
        Peso: 65,
        PlanSuscripcion: "Anual",
        Telefono: 675846201,
        UdGimnasio: "123456789",
        validated: false
    },
    {
        APagar: "50 €",
        Altura: 1.68,
        Apellido1: "Sánchez",
        Apellido2: "López",
        Contraseña: "",
        Email: "ana.sanchez@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "15/06/1990",
        Genero: "Femenino",
        Nombre: "Ana",
        Peso: 62,
        PlanSuscripcion: "Mensual",
        Telefono: 654789321,
        UdGimnasio: "987654321",
        validated: false
    },
    {
        APagar: "600 €",
        Altura: 1.78,
        Apellido1: "Moreno",
        Apellido2: "García",
        Contraseña: "",
        Email: "juan.moreno@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "20/03/1988",
        Genero: "Masculino",
        Nombre: "Juan",
        Peso: 75,
        PlanSuscripcion: "Anual",
        Telefono: 612345678,
        UdGimnasio: "123456789",
        validated: false
    },
    {
        APagar: "50 €",
        Altura: 1.63,
        Apellido1: "Torres",
        Apellido2: "Hernández",
        Contraseña: "",
        Email: "laura.torres@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "05/11/1993",
        Genero: "Femenino",
        Nombre: "Laura",
        Peso: 58,
        PlanSuscripcion: "Mensual",
        Telefono: 698745632,
        UdGimnasio: "987654321",
        validated: false
    },
    {
        APagar: "50 €",
        Altura: 1.75,
        Apellido1: "Ruiz",
        Apellido2: "Álvarez",
        Contraseña: "",
        Email: "miguel.ruiz@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "28/07/1991",
        Genero: "Masculino",
        Nombre: "Miguel",
        Peso: 80,
        PlanSuscripcion: "Mensual",
        Telefono: 633221144,
        UdGimnasio: "987654321",
        validated: false
    },
    {
        APagar: "50 €",
        Altura: 1.67,
        Apellido1: "Díaz",
        Apellido2: "Fernández",
        Contraseña: "",
        Email: "isabel.diaz@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "12/12/1994",
        Genero: "Femenino",
        Nombre: "Isabel",
        Peso: 63,
        PlanSuscripcion: "Mensual",
        Telefono: 644889977,
        UdGimnasio: "123456789",
        validated: false
    },
    {
        APagar: "600 €",
        Altura: 1.72,
        Apellido1: "Vega",
        Apellido2: "Jiménez",
        Contraseña: "",
        Email: "roberto.vega@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "08/02/1989",
        Genero: "Masculino",
        Nombre: "Roberto",
        Peso: 77,
        PlanSuscripcion: "Anual",
        Telefono: 677889900,
        UdGimnasio: "987654321",
        validated: false
    },
    {
        APagar: "600 €",
        Altura: 1.65,
        Apellido1: "Silva",
        Apellido2: "Muñoz",
        Contraseña: "",
        Email: "patricia.silva@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "17/08/1992",
        Genero: "Femenino",
        Nombre: "Patricia",
        Peso: 61,
        PlanSuscripcion: "Anual",
        Telefono: 611223344,
        UdGimnasio: "987654321",
        validated: false
    },
    {
        APagar: "50 €",
        Altura: 1.75,
        Apellido1: "Castro",
        Apellido2: "López",
        Contraseña: "",
        Email: "david.castro@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "30/11/1992",
        Genero: "Masculino",
        Nombre: "David",
        Peso: 82,
        PlanSuscripcion: "Mensual",
        Telefono: 655443322,
        UdGimnasio: "987654321",
        validated: false
    },
    {
        APagar: "50 €",
        Altura: 1.70,
        Apellido1: "Martínez",
        Apellido2: "González",
        Contraseña: "",
        Email: "carlos.martinez@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "13/09/1999",
        Genero: "Masculino",
        Nombre: "Carlos",
        Peso: 79,
        PlanSuscripcion: "Mensual",
        Telefono: 625849200,
        UdGimnasio: "987654321",
        validated: false
    },
    {
        APagar: "600 €",
        Altura: 1.65,
        Apellido1: "Ramírez",
        Apellido2: "Gómez",
        Contraseña: "",
        Email: "maria.ramirez@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "25/04/1995",
        Genero: "Femenino",
        Nombre: "María",
        Peso: 65,
        PlanSuscripcion: "Anual",
        Telefono: 675846201,
        UdGimnasio: "987654321",
        validated: false
    },
    {
        APagar: "50 €",
        Altura: 1.68,
        Apellido1: "Sánchez",
        Apellido2: "Rodríguez",
        Contraseña: "",
        Email: "ana.sanchez@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "15/06/1990",
        Genero: "Femenino",
        Nombre: "Ana",
        Peso: 62,
        PlanSuscripcion: "Mensual",
        Telefono: 654789321,
        UdGimnasio: "DynamicGym",
        validated: false
    },
    {
        APagar: "600 €",
        Altura: 1.78,
        Apellido1: "Moreno",
        Apellido2: "Pablo",
        Contraseña: "",
        Email: "juan.moreno@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "20/03/1988",
        Genero: "Masculino",
        Nombre: "Juan",
        Peso: 75,
        PlanSuscripcion: "Anual",
        Telefono: 612345678,
        UdGimnasio: "DynamicGym",
        validated: false
    },
    {
        APagar: "50 €",
        Altura: 1.63,
        Apellido1: "Torres",
        Apellido2: "García",
        Contraseña: "",
        Email: "laura.torres@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "05/11/1993",
        Genero: "Femenino",
        Nombre: "Laura",
        Peso: 58,
        PlanSuscripcion: "Mensual",
        Telefono: 698745632,
        UdGimnasio: "DynamicGym",
        validated: false
    },
    {
        APagar: "50 €",
        Altura: 1.75,
        Apellido1: "Ruiz",
        Apellido2: "Ángel",
        Contraseña: "",
        Email: "miguel.ruiz@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "28/07/1991",
        Genero: "Masculino",
        Nombre: "Miguel",
        Peso: 80,
        PlanSuscripcion: "Mensual",
        Telefono: 633221144,
        UdGimnasio: "DynamicGym",
        validated: true
    },
    {
        APagar: "50 €",
        Altura: 1.67,
        Apellido1: "Díaz",
        Apellido2: "Fernández",
        Contraseña: "",
        Email: "isabel.diaz@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "12/12/1994",
        Genero: "Femenino",
        Nombre: "Isabel",
        Peso: 63,
        PlanSuscripcion: "Mensual",
        Telefono: 644889977,
        UdGimnasio: "123456789",
        validated: false
    },
    {
        APagar: "600 €",
        Altura: 1.72,
        Apellido1: "Jiménez",
        Apellido2: "Vega",
        Contraseña: "",
        Email: "roberto.jimenez@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "08/02/1989",
        Genero: "Masculino",
        Nombre: "Roberto",
        Peso: 77,
        PlanSuscripcion: "Anual",
        Telefono: 677889900,
        UdGimnasio: "123456789",
        validated: false
    },
    {
        APagar: "600 €",
        Altura: 1.65,
        Apellido1: "Muñoz",
        Apellido2: "Silva",
        Contraseña: "",
        Email: "patricia.munoz@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "17/08/1992",
        Genero: "Femenino",
        Nombre: "Patricia",
        Peso: 61,
        PlanSuscripcion: "Anual",
        Telefono: 611223344,
        UdGimnasio: "DynamicGym",
        validated: false
    },
    {
        APagar: "50 €",
        Altura: 1.75,
        Apellido1: "Castro",
        Apellido2: "López",
        Contraseña: "",
        Email: "david.castro@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "30/11/1992",
        Genero: "Masculino",
        Nombre: "David",
        Peso: 82,
        PlanSuscripcion: "Mensual",
        Telefono: 655443322,
        UdGimnasio: "123456789",
        validated: false
    }
];
export const subirClientes = async () => {
    try {
      // Itera sobre cada cliente y lo sube a Firestore
      for (const cliente of clientes) {
        // Agrega el cliente a la colección "clientes"
        const docRef = await addDoc(collection(db, "clientes"), cliente);
        console.log(`Cliente ${cliente.id} subido con ID: ${docRef.id}`);
      }
      console.log("Todos los clientes han sido subidos.");
    } catch (error) {
      console.error("Error al subir clientes:", error);
    }
  };
