import { initializeApp } from "firebase/app";
import { getFirestore, collection, addDoc } from "firebase/firestore"; // Importa Firestore

// Configuración de Firebase (obtén esto desde la consola de Firebase)
const firebaseConfig = {
  apiKey: "AIzaSyAqnMhZ3u-z1hqlqGod7qUo7bb6PLIF_dI",
  authDomain: "dynamic-dam.firebaseapp.com",
  projectId: "dynamic-dam",
  storageBucket: "dynamic-dam.firebasestorage.app",
  messagingSenderId: "610391208242",
  appId: "1:610391208242:web:31647d9cc6a9ee9b47a72b",
  measurementId: "G-GJFL7VPG07"
};
const app = initializeApp(firebaseConfig);

const db = getFirestore(app); // Inicializa Firestore

export const clientes = [
    {
        id: 1,
        APagar: "50 €",
        Altura: 1.70,
        Apellido1: "Martinez",
        Apellido2: "López",
        Contraseña: "",
        Email: "carlosml@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "13/09/1999",
        Genero: "Masculino",
        Nombre: "Carlos",
        Peso: 79,
        PlanSuscripcion: "Mensual",
        Telefono: 625849200,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 2,
        APagar: "600 €",
        Altura: 1.65,
        Apellido1: "Gómez",
        Apellido2: "Ramírez",
        Contraseña: "",
        Email: "mariagr@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "25/04/1995",
        Genero: "Femenino",
        Nombre: "Maria",
        Peso: 65,
        PlanSuscripcion: "Anual",
        Telefono: 675846201,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 3,
        APagar: "50 €",
        Altura: 1.68,
        Apellido1: "Rodríguez",
        Apellido2: "Sánchez",
        Contraseña: "",
        Email: "anars@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "15/06/1990",
        Genero: "Femenino",
        Nombre: "Ana",
        Peso: 62,
        PlanSuscripcion: "Mensual",
        Telefono: 654789321,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 4,
        APagar: "600 €",
        Altura: 1.78,
        Apellido1: "Pablo",
        Apellido2: "Moreno",
        Contraseña: "",
        Email: "juanpm@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "20/03/1988",
        Genero: "Masculino",
        Nombre: "Juan",
        Peso: 75,
        PlanSuscripcion: "Anual",
        Telefono: 612345678,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 5,
        APagar: "50 €",
        Altura: 1.63,
        Apellido1: "García",
        Apellido2: "Torres",
        Contraseña: "",
        Email: "lauragt@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "05/11/1993",
        Genero: "Femenino",
        Nombre: "Laura",
        Peso: 58,
        PlanSuscripcion: "Mensual",
        Telefono: 698745632,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 6,
        APagar: "50 €",
        Altura: 1.75,
        Apellido1: "Ángel",
        Apellido2: "Ruiz",
        Contraseña: "",
        Email: "miguelar@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "28/07/1991",
        Genero: "Masculino",
        Nombre: "Miguel",
        Peso: 80,
        PlanSuscripcion: "Mensual",
        Telefono: 633221144,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 7,
        APagar: "50 €",
        Altura: 1.67,
        Apellido1: "Fernández",
        Apellido2: "Díaz",
        Contraseña: "",
        Email: "isabelfd@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "12/12/1994",
        Genero: "Femenino",
        Nombre: "Isabel",
        Peso: 63,
        PlanSuscripcion: "Mensual",
        Telefono: 644889977,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 8,
        APagar: "600 €",
        Altura: 1.72,
        Apellido1: "Jiménez",
        Apellido2: "Vega",
        Contraseña: "",
        Email: "robertojv@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "08/02/1989",
        Genero: "Masculino",
        Nombre: "Roberto",
        Peso: 77,
        PlanSuscripcion: "Anual",
        Telefono: 677889900,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 9,
        APagar: "600 €",
        Altura: 1.65,
        Apellido1: "Muñoz",
        Apellido2: "Silva",
        Contraseña: "",
        Email: "patriciams@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "17/08/1992",
        Genero: "Femenino",
        Nombre: "Patricia",
        Peso: 61,
        PlanSuscripcion: "Anual",
        Telefono: 611223344,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 10,
        APagar: "50 €",
        Altura: 1.75,
        Apellido1: "López",
        Apellido2: "Castro",
        Contraseña: "",
        Email: "davidlc@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "30/11/1992",
        Genero: "Masculino",
        Nombre: "David",
        Peso: 82,
        PlanSuscripcion: "Mensual",
        Telefono: 655443322,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 11,
        APagar: "50 €",
        Altura: 1.70,
        Apellido1: "Martinez",
        Apellido2: "López",
        Contraseña: "",
        Email: "carlosml@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "13/09/1999",
        Genero: "Masculino",
        Nombre: "Carlos",
        Peso: 79,
        PlanSuscripcion: "Mensual",
        Telefono: 625849200,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 12,
        APagar: "600 €",
        Altura: 1.65,
        Apellido1: "Gómez",
        Apellido2: "Ramírez",
        Contraseña: "",
        Email: "mariagr@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "25/04/1995",
        Genero: "Femenino",
        Nombre: "Maria",
        Peso: 65,
        PlanSuscripcion: "Anual",
        Telefono: 675846201,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 13,
        APagar: "50 €",
        Altura: 1.68,
        Apellido1: "Rodríguez",
        Apellido2: "Sánchez",
        Contraseña: "",
        Email: "anars@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "15/06/1990",
        Genero: "Femenino",
        Nombre: "Ana",
        Peso: 62,
        PlanSuscripcion: "Mensual",
        Telefono: 654789321,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 14,
        APagar: "600 €",
        Altura: 1.78,
        Apellido1: "Pablo",
        Apellido2: "Moreno",
        Contraseña: "",
        Email: "juanpm@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "20/03/1988",
        Genero: "Masculino",
        Nombre: "Juan",
        Peso: 75,
        PlanSuscripcion: "Anual",
        Telefono: 612345678,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 15,
        APagar: "50 €",
        Altura: 1.63,
        Apellido1: "García",
        Apellido2: "Torres",
        Contraseña: "",
        Email: "lauragt@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "05/11/1993",
        Genero: "Femenino",
        Nombre: "Laura",
        Peso: 58,
        PlanSuscripcion: "Mensual",
        Telefono: 698745632,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 16,
        APagar: "50 €",
        Altura: 1.75,
        Apellido1: "Ángel",
        Apellido2: "Ruiz",
        Contraseña: "",
        Email: "miguelar@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "28/07/1991",
        Genero: "Masculino",
        Nombre: "Miguel",
        Peso: 80,
        PlanSuscripcion: "Mensual",
        Telefono: 633221144,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 17,
        APagar: "50 €",
        Altura: 1.67,
        Apellido1: "Fernández",
        Apellido2: "Díaz",
        Contraseña: "",
        Email: "isabelfd@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "12/12/1994",
        Genero: "Femenino",
        Nombre: "Isabel",
        Peso: 63,
        PlanSuscripcion: "Mensual",
        Telefono: 644889977,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 18,
        APagar: "600 €",
        Altura: 1.72,
        Apellido1: "Jiménez",
        Apellido2: "Vega",
        Contraseña: "",
        Email: "robertojv@gmail.com",
        EstadoSuscripcion: false,
        FechaNacimiento: "08/02/1989",
        Genero: "Masculino",
        Nombre: "Roberto",
        Peso: 77,
        PlanSuscripcion: "Anual",
        Telefono: 677889900,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 19,
        APagar: "600 €",
        Altura: 1.65,
        Apellido1: "Muñoz",
        Apellido2: "Silva",
        Contraseña: "",
        Email: "patriciams@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "17/08/1992",
        Genero: "Femenino",
        Nombre: "Patricia",
        Peso: 61,
        PlanSuscripcion: "Anual",
        Telefono: 611223344,
        UdGimnasio: "DynamicGym"
    },
    {
        id: 20,
        APagar: "50 €",
        Altura: 1.75,
        Apellido1: "López",
        Apellido2: "Castro",
        Contraseña: "",
        Email: "davidlc@gmail.com",
        EstadoSuscripcion: true,
        FechaNacimiento: "30/11/1992",
        Genero: "Masculino",
        Nombre: "David",
        Peso: 82,
        PlanSuscripcion: "Mensual",
        Telefono: 655443322,
        UdGimnasio: "DynamicGym"
    }
];
export const subirClientes = async () => {
    try {
      // Itera sobre cada cliente y lo sube a Firestore
      for (const cliente of clientes) {
        // Agrega el cliente a la colección "clientes"
        const docRef = await addDoc(collection(db, "clientes"), cliente);
        console.log(`Cliente ${cliente.id} subido con ID: ${docRef.id}`);
      }
      console.log("Todos los clientes han sido subidos.");
    } catch (error) {
      console.error("Error al subir clientes:", error);
    }
  };
